exports.UserInfoStatus = {
	USERIDMISSING : 1,
	BABYNAMEMISSING : 2,
	BIRTHDAYMISSING : 3,
	LOCATIONMISSING : 4,
	COMPLETED : 0
};

exports.states = {
    BABYNAMEMODE : '_BABYNAMEMODE',
    BIRTHDAYMODE : '_BIRTHDAYMODE',
    LCATIONMODE : '_LOCATIONMODE'
};
